# Generated by Django 4.2.2 on 2023-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
