# Generated by Django 4.2.2 on 2023-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_liter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='countStock',
        ),
    ]
